# Generated by Django 4.0 on 2022-06-26 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('changApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactlist',
            old_name='title',
            new_name='head',
        ),
    ]
